#PumpkiNibble
#1 healAmount is half a heart or food
#Duration is in seconds
#Enabling trippy netherwart may get annoying.
#If you do not specify a duration and dtrength for every potion, you will get a
#NullPointerException
items:
  pumpkin:
    enabled: true
    healFoodAmount: 1
    healHealthAmount: 0
    itemAmount: 10
    potionEffects:
      regen:
        strength: 1
        duration: 1
    messageOnEat: 'You nibbled on some seeds'
    messageInsufficient: 'Too..little..seeds..must..satisfy..cravings!'
    messageUnable: 'Doesnt seem like you are able to nibble on any seeds'
  cocoa:
    enabled: true
    healFoodAmount: 1
    healHealthAmount: 0
    itemAmount: 10
    potionEffects: []
    potionStrength: []
    potionDuration: []
    messageOnEat: 'Mhm..Chocolatey'
    messageInsufficient: 'MOAR CHOCOLATE NAO!!'
    messageUnable: 'Doesnt seem like you can nibble any cocoa'
  netherwart:
    enabled: false
    itemAmount: 10
    potionEffects: 
      nausea:
        strength: 10
        duration: 10
    messageOnEat: 'Eh he he he'
    messageInsufficient: 'Need..more..'
    messageUnable: 'You cant take &mdrugs &ruh.. nevermind.'
  milk:
    enabled: false
    itemAmount: 1
    potionEffects: 
      nausea:
        strength: 5
        duration: 10
    messageOnEat: 'Ooh, this milk is strong!'
    messageInsufficient: 'Hit me again!'
    messageUnable: 'Doesnt seem like youre legal age yet'
  wheat:
    enabled: true
    healFoodAmount: 1
    healHealthAmount: 0
    itemAmount: 10
    potionEffects: []
    messageOnEat: 'Bleh, bland wheat'
    messageInsufficient: 'You must be hungry, eat some more wheat'
    messageUnable: 'No wheat for you'
  fermentedeye:
    enabled: false
    itemAmount: 1
    potionEffects: 
      poison:
        strength: 10
        duration: 2
      nausea:
        strength: 10
        duration: 2
    messageOnEat: 'Just disgusting, egh'
    messageInsufficient: 'Nope'
    messageUnable: 'Why would you want to eat this anyways?'
    potionDuration: 
      poison: 10
      nausea: 10
  slimeball:
    enabled: false
    itemAmount: 1
    potionEffects: 
      jump:
        strength: 2
        duration: 10
    messageOnEat: 'Slimy, but you feel a bounce in your step'
    messageInsufficient: 'Slimy, but a bit sweet. You search for more'
    messageUnable: 'The slimeball splatters on your face'
  sugar:
    enabled: false
    itemAmount: 16
    potionEffects: 
      jump:
        strength: 5
        duration: 60
      speed:
        strength: 5
        duration: 60
    messageOnEat: 'SUGAR RUSH!'
    messageInsufficient: 'Your odd sugar cravings have not been realised'
    messageUnable: 'No raw sugar for you. Its bad for your teeth'
  goldmelon:
    enabled: true
    healFoodAmount: 0
    healHealthAmount: 20
    itemAmount: 1
    potionEffects:
      regen:
        strength: 4
        duration: 60
    messageOnEat: 'Golden watermelon juice washes over you, rejuevinating you.'
    messageInsufficient: 'You feel as if you need more'
    messageUnable: 'What? You cant afford to eat that!'
  sugarcane:
    enabled: false
    itemAmount: 8
    potionEffects: 
      jump:
        strength: 1
        duration: 20
      speed:
        strength: 1
        duration: 20 
    messageOnEat: 'Chewing sugarcane is awesome!'
    messageInsufficient: 'You need more to get enough sugarcane juice out of it'
    messageUnable: 'No sugar for you. Its bad for your teeth'
  brownmushroom:
    enabled: false
    itemAmount: 1
    potionEffects: 
      poison:
        strength: 2
        duration: 10
      nausea:
        strength: 10
        duration: 10
    messageOnEat: 'Brown mushrooms are poisonous unless cooked'
    messageInsufficient: 'Nope'
    messageUnable: 'Why would you want to eat this anyways?'
  redmushroom:
    enabled: false
    itemAmount: 1
    potionEffects: 
      poison:
        strength: 2
        duration: 10
      nausea:
        strength: 10
        duration: 10
    messageOnEat: 'Red mushrooms are poisonous unless coocked'
    messageInsufficient: 'Nope'
    messageUnable: 'Why would you want to eat this anyways?'
#Do not change
#This section is for reference only.
validPotionEffects:
  - regen
  - heal
  - harm
  - poison
  - hunger
  - nightvision
  - weakness
  - jump
  - resistance
  - fireresist
  - waterbreathing
  - invisibility
  - slowmine
  - slow
  - fastmine
  - speed
  - nausea
  - blindness
  
