#PumpkiNibble Config File
#To define new items, follow this template
#=========================================
#pumpkin: Defines permission name, not quite as important user-wise, can be anything you want
#id: Defines item ID, be very careful
#data: Defines data value, default items have a value of zero, other items use data values (such as cocoa beans)
#enabled: Whether this is enabled or not
#takeInsufficientItems: Do we want the item to be taken if we don't have enough to "eat" it?
#healFoodAmount: Amount of the food bar to heal. One is half a "drumstick"
#healHealthAmount: Amount of hearts to heal. One is half a heart
#itemAmount: How much is the minimum amount of items? 
#potionEffects: List of potionEffects, see examples, duration is in seconds.
#potionEffects use the internal Bukkit names, see validPotionEffects
#messageOnEat: Message that is displayed when item is eaten
#messageInsufficient: Message that is displayed when not enough items are eaten at once
#messageUnable: Permissions message, when user is not allowed to eat items
#blacklist: List of blocks, that, when clicked will not trigger eating, such as farmland, doors, etc. It is recommended you copy the section from the defaults.


items:
  pumpkin:
    data: 
      id: 361
      dmg: 0
    enabled: true
    takeInsufficientItems: false
    healFoodAmount: 1
    healHealthAmount: 0
    itemAmount: 10
    potionEffects:
      regeneration:
        strength: 1
        duration: 10
    messageOnEat: 'You nibbled on some seeds'
    messageInsufficient: 'Too..little..seeds..must..satisfy..cravings!'
    messageUnable: 'Doesnt seem like you are able to nibble on any seeds'
    blacklist:
      - 60 
      - 54
      - 64
      - 77
      - 143
      - 69
      - 96
      - 107
  cocoa:
    enabled: true
    healFoodAmount: 1
    healHealthAmount: 0
    itemAmount: 10
    potionEffects: []
    potionStrength: []
    potionDuration: []
    messageOnEat: 'Mhm..Chocolatey'
    messageInsufficient: 'MOAR CHOCOLATE NAO!!'
    messageUnable: 'Doesnt seem like you can nibble any cocoa'
  netherwart:
    enabled: false
    itemAmount: 10
    potionEffects: 
      confusion:
        strength: 10
        duration: 10
    messageOnEat: 'Eh he he he'
    messageInsufficient: 'Need..more..'
    messageUnable: 'You cant take &mdrugs &ruh.. nevermind.'
  milk:
    enabled: false
    itemAmount: 1
    potionEffects: 
      confusion:
        strength: 5
        duration: 10
    messageOnEat: 'Ooh, this milk is strong!'
    messageInsufficient: 'Hit me again!'
    messageUnable: 'Doesnt seem like youre legal age yet'
  wheat:
    enabled: true
    healFoodAmount: 1
    healHealthAmount: 0
    itemAmount: 10
    potionEffects: []
    messageOnEat: 'Bleh, bland wheat'
    messageInsufficient: 'You must be hungry, eat some more wheat'
    messageUnable: 'No wheat for you'
  fermentedeye:
    enabled: false
    itemAmount: 1
    potionEffects: 
      poison:
        strength: 10
        duration: 2
      confusion:
        strength: 10
        duration: 2
    messageOnEat: 'Just disgusting, egh'
    messageInsufficient: 'Nope'
    messageUnable: 'Why would you want to eat this anyways?'
  slimeball:
    enabled: false
    itemAmount: 1
    potionEffects: 
      jump:
        strength: 2
        duration: 10
    messageOnEat: 'Slimy, but you feel a bounce in your step'
    messageInsufficient: 'Slimy, but a bit sweet. You search for more'
    messageUnable: 'The slimeball splatters on your face'
  sugar:
    enabled: false
    itemAmount: 16
    potionEffects: 
      jump:
        strength: 5
        duration: 60
      speed:
        strength: 5
        duration: 60
    messageOnEat: 'SUGAR RUSH!'
    messageInsufficient: 'Your odd sugar cravings have not been realised'
    messageUnable: 'No raw sugar for you. Its bad for your teeth'
  goldmelon:
    enabled: true
    healFoodAmount: 0
    healHealthAmount: 20
    itemAmount: 1
    potionEffects:
      regeneration:
        strength: 4
        duration: 60
    messageOnEat: 'Golden watermelon juice washes over you, rejuevinating you.'
    messageInsufficient: 'You feel as if you need more'
    messageUnable: 'What? You cant afford to eat that!'
  sugarcane:
    enabled: false
    itemAmount: 8
    potionEffects: 
      jump:
        strength: 1
        duration: 20
      speed:
        strength: 1
        duration: 20 
    messageOnEat: 'Chewing sugarcane is awesome!'
    messageInsufficient: 'You need more to get enough sugarcane juice out of it'
    messageUnable: 'No sugar for you. Its bad for your teeth'
  brownmushroom:
    enabled: false
    itemAmount: 1
    potionEffects: 
      poison:
        strength: 2
        duration: 10
      confusion:
        strength: 10
        duration: 10
    messageOnEat: 'Brown mushrooms are poisonous unless cooked'
    messageInsufficient: 'Nope'
    messageUnable: 'Why would you want to eat this anyways?'
  redmushroom:
    enabled: false
    itemAmount: 1
    potionEffects: 
      poison:
        strength: 2
        duration: 10
      confusion:
        strength: 10
        duration: 10
    messageOnEat: 'Red mushrooms are poisonous unless coocked'
    messageInsufficient: 'Nope'
    messageUnable: 'Why would you want to eat this anyways?'
#Do not change
#This section is for reference only.
validPotionEffects:
  - blindness
  - confusion
  - damage_resistance
  - fast_digging
  - fire_resistance
  - harm
  - heal
  - hunger
  - increase_damage
  - invisibility
  - jump
  - night_vision
  - poison
  - regeneration
  - slow
  - slow_digging
  - speed
  - water_breathing
  - weakness
  - wither
  
