#PumpkiNibble Config File
#To define new items, follow this template
#=========================================
#pumpkin: Defines permission name, not quite as important user-wise, can be anything you want
#id: Defines item ID, be very careful
#data: Defines data value, default items have a value of zero, other items use data values (such as cocoa beans)
#enabled: Whether this is enabled or not
#takeInsufficientItems: Do we want the item to be taken if we don't have enough to "eat" it?
#healFoodAmount: Amount of the food bar to heal. One is half a "drumstick"
#healHealthAmount: Amount of hearts to heal. One is half a heart
#itemAmount: How much is the minimum amount of items? 
#potionEffects: List of potionEffects, see examples, duration is in seconds.
#potionEffects use the internal Bukkit names, see validPotionEffects
#messageOnEat: Message that is displayed when item is eaten
#messageInsufficient: Message that is displayed when not enough items are eaten at once
#messageUnable: Permissions message, when user is not allowed to eat items
#blacklist: List of blocks, that, when clicked will not trigger eating, such as farmland, doors, etc. It is recommended you copy the section from the defaults.


items:
  pumpkin:
    data: 
      id: 361
      dmg: 0
    enabled: true
    takeInsufficientItems: false
    healFoodAmount: 3
    healHealthAmount: 0
    itemAmount: 10
    potionEffects:
      regeneration:
        strength: 1
        duration: 10
    messageOnEat: 'You nibbled on some seeds'
    messageInsufficient: 'Too..little..seeds..must..satisfy..cravings!'
    messageUnable: 'Doesnt seem like you are able to nibble on any seeds'
    blacklist:
      - 60 
      - 54
      - 64
      - 77
      - 143
      - 69
      - 96
      - 61
      - 62
      - 107
      - 117
      - 145
  cocoa:
    data:
      id: 351
      dmg: 3
    enabled: true
    takeInsufficientItems: false
    healFoodAmount: 2
    healHealthAmount: 1
    itemAmount: 2
    potionEffects: []
    messageOnEat: 'You ate some chocolate'
    messageInsufficient: 'You eat some chocolate, but unhuman cravings threaten to ravage your cocoa bean stock'
    messageUnable: 'You are not allowed to eat cocoa beans'
    blacklist:
      - 60 
      - 54
      - 64
      - 77
      - 143
      - 69
      - 96
      - 61
      - 62
      - 107
      - 17
      - 117
      - 145
  netherwart:
    data:
      id: 372
      dmg: 0
    enabled: false
    takeInsufficientItems: true
    healFoodAmount: 0
    healHealthAmount 0 
    itemAmount: 15
    potionEffects:
      confusion:
        strength: 6
        duration: 300
    messageOnEat: '&kYo&ru are s&3o fli&kpp&4in&ig hi&2gh'
    messageInsufficient: 'Wasn''t I supposed to start hallucinating? Maybe try a dose of 15'
    messageUnable: 'You don''t want to do drugs'
    blacklist: 
      - 54
      - 64
      - 77
      - 143
      - 69
      - 96
      - 107
      - 88
      - 61
      - 62
      - 117
      - 145
  goldencarrot:
    data:
      id: 396
      dmg: 0
    enabled: true
    takeInsufficientItems: false
    healFoodAmount: 0
    healHealthAmount: 3
    itemAmount: 2
    potionEffects:
      night_vision:
        strength: 2
        duration: 60
      invisibility:
        strength: 2
        duration: 60
    messageOnEat: 'The miraculous powers of the carrot flow into you, as you see the world with sharper eyes, and feel your body vanish'
    messageInsufficient: 'You bite into the carrot, but the infused gold render it inedible. Reverse logic dictates you must eat more'
    messageUnable: 'The powers of the carrot may not be bestowed upon you, young one'
        blacklist: 
      - 54
      - 64
      - 77
      - 143
      - 69
      - 96
      - 107
      - 61
      - 62
      - 117
      - 145
  goldenmelon:
    data:
      id: 382
      dmg: 0
    enabled: true
    takeInsufficientItems: false
    healFoodAmount: 0
    healHealthAmount: 0
    itemAmount: 1
    potionEffects:
      regeneration:
        strength: 2
        duration: 60
    messageOnEat: 'Your body warms, as you feel new strength pour in you'
    messageInsufficient: 'You bite into the melon, but the infused gold render it inedible. Reverse logic dictates you must eat more'
    messageUnable: 'A mysterious force surrounding the slice prevents your mouth from making contact with it''s golden juice'
    blacklist: 
      - 54
      - 64
      - 77
      - 143
      - 69
      - 96
      - 107
      - 61
      - 62
      - 117
      - 145
  sugarcane:
    data:
      id: 338
      dmg: 0
    enabled: true
    takeInsufficientItems: true
    healFoodAmount: 0
    healHealthAmount: 0
    itemAmount: 10
    potionEffects:
      jump:
        strength: 2
        duration: 20
      speed:
        strength: 2
        duration: 20
    messageOnEat: 'The cooling sugarcane juice reinvigorates you'
    messageInsufficient: 'This is not enough sugarcane to make even a cup of juice!'
    messageUnable: 'A mysterious force surrounding the slice prevents your mouth from making contact with it''s golden juice'
    blacklist: 
      - 54
      - 64
      - 77
      - 143
      - 69
      - 96
      - 107
      - 61
      - 62
      - 117
      - 145
      - 2
      - 3
      - 12
  brownmushroom:
    data:
      id: 39
      dmg: 0
    enabled: false
    takeInsufficientItems: true
    healFoodAmount: 0
    healHealthAmount: 0
    itemAmount: 1
    potionEffects:
      poison:
        strength: 1
        duration: 20
    messageOnEat: 'You''re supposed to &ocook&r the mushrooms before eating them!'
    messageInsufficient: 'Good thing you didn''t eat you much, you could have gotten sick'
    messageUnable: 'Something is preventing you from eating the mushroom. Probably the permissions system.'
    blacklist: 
      - 54
      - 64
      - 77
      - 143
      - 69
      - 96
      - 107
      - 61
      - 62
      - 117
      - 145
      - 2
      - 3
      - 12
      - 1
      - 110
  redmushroom:
    data:
      id: 40
      dmg: 0
    enabled: false
    takeInsufficientItems: true
    healFoodAmount: 0
    healHealthAmount: 0
    itemAmount: 1
    potionEffects:
      nausea:
        strength: 1
        duration: 20
    messageOnEat: 'You''re supposed to &ocook&r the mushrooms before eating them!'
    messageInsufficient: 'Good thing you didn''t eat you much, you could have gotten sick'
    messageUnable: 'Something is preventing you from eating the mushroom. Probably the permissions system.'
    blacklist: 
      - 54
      - 64
      - 77
      - 143
      - 69
      - 96
      - 107
      - 61
      - 62
      - 117
      - 145
      - 2
      - 3
      - 12
      - 1
      - 110
#Do not change
#This section is for reference only.
validPotionEffects:
  - blindness
  - confusion
  - damage_resistance
  - fast_digging
  - fire_resistance
  - harm
  - heal
  - hunger
  - increase_damage
  - invisibility
  - jump
  - night_vision
  - poison
  - regeneration
  - slow
  - slow_digging
  - speed
  - water_breathing
  - weakness
  - wither
  
