name: PumpkiNibble
main: net.mystia.PumpkiNibble.PumpkiNibbleMain
version: 2.1
description: Lets you nibble on pumpkin seeds. This plugin may lead to excessive and or compulsive consumption of pumpkin seeds in Minecraft and Real Life enviroments. ron975 is not liable for any addictions, injuries and pumpkin seed shortages relating to this plugin and pumpkin seeds.
author: ron975
permissions:
  pumpkinibble.nibble.all:
    description: Lets you nibble on all things.
    default: true

  pumpkinibble.admin.reload:
      description: Lets you reload the config.
      
commands:
   pumpkinibble:
      description: Main Command.
      usage: /pumpkinibble 
      permission: pumpkinibble.admin.reload
      permission-message: You can't reload PumpkiNibble