#PumpkiNibble
#1 healAmount is half a heart or food
#Duration is in seconds
#Enabling trippy netherwart may get annoying.
pumpkin:
  enabled: true
  healFoodAmount: 1
  healHealthAmount: 0
  itemAmount: 10
  potionEffects:
    - regen
  potionStrength: 1
  potionDuration: 10
cocoa:
  enabled: true
  healFoodAmount: 1
  healHealthAmount: 0
  itemAmount: 10
  potionEffects: []
  potionStrength: 1
  potionDuration: 10
netherwart:
  enabled: false
  itemAmount: 10
  potionEffects: 
    - nausea
  potionStrength: 1
  potionDuration: 10
validPotionEffects:
  - regen
  - heal
  - harm
  - poison
  - hunger
  - nightvision
  - weakness
  - jump
  - resistance
  - fireresist
  - waterbreathing
  - invisibility
  - slowmine
  - slow
  - fastmine
  - speed
  - nausea